version: '3.8'

services:
  # n8n Community Edition
  n8n:
    image: n8nio/n8n:latest
    container_name: secure-dsa-pro-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=secure-dsa-pro-2024
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=UTC
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - secure-dsa-network

  # MCP Server for Claude 3.5 (Primary)
  mcp-claude-primary:
    image: ollama/ollama:latest
    container_name: secure-dsa-pro-claude-primary
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - claude_primary_data:/root/.ollama
    networks:
      - secure-dsa-network
    command: >
      sh -c "
        ollama pull claude-3.5-sonnet &&
        ollama serve
      "

  # MCP Server for Deepseek v3 (Secondary)
  mcp-deepseek-secondary:
    image: ollama/ollama:latest
    container_name: secure-dsa-pro-deepseek-secondary
    restart: unless-stopped
    ports:
      - "11436:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - deepseek_secondary_data:/root/.ollama
    networks:
      - secure-dsa-network
    command: >
      sh -c "
        ollama pull deepseek-coder:33b &&
        ollama serve
      "

  # MCP Server for GPT-4.1 (Retry Model 1)
  mcp-gpt41-retry1:
    image: ollama/ollama:latest
    container_name: secure-dsa-pro-gpt41-retry1
    restart: unless-stopped
    ports:
      - "11435:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - gpt41_retry1_data:/root/.ollama
    networks:
      - secure-dsa-network
    command: >
      sh -c "
        ollama pull gpt4.1 &&
        ollama serve
      "

  # MCP Server for Grok4 (Retry Model 2)
  mcp-grok4-retry2:
    image: ollama/ollama:latest
    container_name: secure-dsa-pro-grok4-retry2
    restart: unless-stopped
    ports:
      - "11437:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - grok4_retry2_data:/root/.ollama
    networks:
      - secure-dsa-network
    command: >
      sh -c "
        ollama pull grok4 &&
        ollama serve
      "

  # Health check service
  health-check:
    image: curlimages/curl:latest
    container_name: secure-dsa-pro-health
    restart: unless-stopped
    depends_on:
      - n8n
      - mcp-claude-primary
      - mcp-deepseek-secondary
      - mcp-gpt41-retry1
      - mcp-grok4-retry2
    networks:
      - secure-dsa-network
    command: >
      sh -c "
        echo 'Waiting for services to start...' &&
        sleep 30 &&
        echo 'Checking n8n...' &&
        curl -f http://n8n:5678/healthz || exit 1 &&
        echo 'Checking Claude 3.5 (Primary)...' &&
        curl -f http://mcp-claude-primary:11434/api/tags || exit 1 &&
        echo 'Checking Deepseek v3 (Secondary)...' &&
        curl -f http://mcp-deepseek-secondary:11434/api/tags || exit 1 &&
        echo 'Checking GPT-4.1 (Retry 1)...' &&
        curl -f http://mcp-gpt41-retry1:11434/api/tags || exit 1 &&
        echo 'Checking Grok4 (Retry 2)...' &&
        curl -f http://mcp-grok4-retry2:11434/api/tags || exit 1 &&
        echo 'All services are healthy!' &&
        while true; do sleep 60; done
      "

volumes:
  n8n_data:
    driver: local
  claude_primary_data:
    driver: local
  deepseek_secondary_data:
    driver: local
  gpt41_retry1_data:
    driver: local
  grok4_retry2_data:
    driver: local

networks:
  secure-dsa-network:
    driver: bridge 